name: unit testing
run-name: CI tests
on: [push]
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      #- name: check insecure for vuln
       # run: cd insecure && npm i && npm audit  
